# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Testmyapp < Formula
  desc "Cli for testmyapp.io"
  homepage "https://github.com/gjergj/testmyapp"
  version "0.0.75"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gjergj/testmyapp/releases/download/v0.0.75/testmyapp_Darwin_x86_64.tar.gz"
      sha256 "af5982a456e99ee7f7fc5049d6ea501214ce6b351f0dbd81a32a59f3b507a6a1"

      def install
        bin.install "testmyapp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gjergj/testmyapp/releases/download/v0.0.75/testmyapp_Darwin_arm64.tar.gz"
      sha256 "200b299baf2a61077c7d809432336988c8d57863d2ec58c520c08dfcf355ba71"

      def install
        bin.install "testmyapp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Gjergj/testmyapp/releases/download/v0.0.75/testmyapp_Linux_x86_64.tar.gz"
      sha256 "fd0be512ec2e838303b1f350feca2839c4196f878b92dffce00d661a11c916e3"

      def install
        bin.install "testmyapp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gjergj/testmyapp/releases/download/v0.0.75/testmyapp_Linux_arm64.tar.gz"
      sha256 "94b1b6b66a335ae15aba6ed0da4fb6c3f6bfc6da79ed7c23789d739fd2925545"

      def install
        bin.install "testmyapp"
      end
    end
  end
end
